Fix dodgy indentation in python
A mix of tabs and spaces caused a python error which in turn leads to a
segfault in fluidity due to our handling of the exception (proposed fix
in https://github.com/FluidityProject/fluidity/pull/321) as reported
in https://github.com/FluidityProject/fluidity/issues/315.

After fixing the indentation, we now get the following error in running
the .xml python validation tests:

Stokes_subduction_zone_vanKeken2008_TwoB: Assigning variables:
from fluidity_tools import stat_parser
s = stat_parser("vanKekenTwoB.detectors")
T = s["Fluid"]["Temperature"]["Temperature6060"][-1]
Temperature6060 = T-(273.)
Variable computation raised an exception
--------------------------------------------------------------------------------
  1  from fluidity_tools import stat_parser
  2  s = stat_parser("vanKekenTwoB.detectors")
  3  T = s["Fluid"]["Temperature"]["Temperature6060"][-1]
  4  Temperature6060 = T-(273.)
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/data1/git/fluidity/python/fluidity/regressiontest.py", line 304, in run_python
    exec(self.code, varsdict)
  File "<string>", line 2, in <module>
  File "/data1/git/fluidity/tools/../python/fluidity_tools.py", line 325, in __init__
    statfile=open(filename, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'vanKekenTwoB.detectors'
--------------------------------------------------------------------------------

which I think is because the detectors are now written in hdf5 so can't
be read using stat_parser anymore.